@api =  http://localhost:4000/products 
###
GET   {{api}}
###
POST {{api}}
Content-Type: application/json

{
  "Name": "teclado rjo",
  "Description": "es de color rojo",
  "Quantity": 14
}

###
GET {{api}}/14
###
DELETE {{api}}/14

###
GET {{api}}/count
### update
PUT {{api}}/14
Content-Type: application/json

{
  "Name": "teclado rojo modificado",
  "Description": "es de color rojo con blanco",
  "Quantity": 7
}
