@api =  http://localhost:4000/products 
###
GET   {{api}}
###
POST {{api}}
Content-Type: application/json

{
  "Name": "udifonos verdes",
  "Description": "son de color verde",
  "Quantity": 2,
  "status" :"1"
}

###
GET {{api}}/20
###
DELETE {{api}}/23

###
GET {{api}}/count
### update
PUT {{api}}/18
Content-Type: application/json

{
  "Name": "dsdgdssdfgfgfg",
  "Description": "Hizo un reporte de comparativa bd",
  "Quantity": 20
}
